from server import util
from server.models.base_model_ import Model


class AccessToken(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, access_token: str = None):  # noqa: E501
        """AccessToken - a model defined in Swagger

        :param access_token: The access_token of this AccessToken.  # noqa: E501
        :type access_token: str
        """
        self.swagger_types = {
            "access_token": str,
        }

        self.attribute_map = {
            "access_token": "access_token",
        }
        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt) -> "AccessToken":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccessToken of this AccessToken.  # noqa: E501
        :rtype: AccessToken
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this AccessToken.


        :return: The access_token of this AccessToken.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this AccessToken.


        :param access_token: The access_token of this AccessToken.
        :type access_token: str
        """

        self._access_token = access_token
