# coding: utf-8

from __future__ import absolute_import

from server import util
from server.models.base_model_ import Model


class Body2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bundle_name: str=None, workspace_id: str=None, user_id: str=None):  # noqa: E501
        """Body2 - a model defined in Swagger

        :param bundle_name: The bundle_name of this Body2.  # noqa: E501
        :type bundle_name: str
        :param workspace_id: The workspace_id of this Body2.  # noqa: E501
        :type workspace_id: str
        :param user_id: The user_id of this Body2.  # noqa: E501
        :type user_id: str
        """
        self.swagger_types = {
            'bundle_name': str,
            'workspace_id': str,
            'user_id': str
        }

        self.attribute_map = {
            'bundle_name': 'bundleName',
            'workspace_id': 'workspaceId',
            'user_id': 'userId'
        }
        self._bundle_name = bundle_name
        self._workspace_id = workspace_id
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_2 of this Body2.  # noqa: E501
        :rtype: Body2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bundle_name(self) -> str:
        """Gets the bundle_name of this Body2.


        :return: The bundle_name of this Body2.
        :rtype: str
        """
        return self._bundle_name

    @bundle_name.setter
    def bundle_name(self, bundle_name: str):
        """Sets the bundle_name of this Body2.


        :param bundle_name: The bundle_name of this Body2.
        :type bundle_name: str
        """

        self._bundle_name = bundle_name

    @property
    def workspace_id(self) -> str:
        """Gets the workspace_id of this Body2.


        :return: The workspace_id of this Body2.
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id: str):
        """Sets the workspace_id of this Body2.


        :param workspace_id: The workspace_id of this Body2.
        :type workspace_id: str
        """

        self._workspace_id = workspace_id

    @property
    def user_id(self) -> str:
        """Gets the user_id of this Body2.


        :return: The user_id of this Body2.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this Body2.


        :param user_id: The user_id of this Body2.
        :type user_id: str
        """

        self._user_id = user_id
