# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server import util


class PreferedWorkspace(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, default_workspace_id: str=None, user_id: str=None):  # noqa: E501
        """PreferedWorkspace - a model defined in Swagger

        :param default_workspace_id: The default_workspace_id of this PreferedWorkspace.  # noqa: E501
        :type default_workspace_id: str
        :param user_id: The user_id of this PreferedWorkspace.  # noqa: E501
        :type user_id: str
        """
        self.swagger_types = {
            'default_workspace_id': str,
            'user_id': str
        }

        self.attribute_map = {
            'default_workspace_id': 'defaultWorkspaceId',
            'user_id': 'userId'
        }
        self._default_workspace_id = default_workspace_id
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'PreferedWorkspace':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PreferedWorkspace of this PreferedWorkspace.  # noqa: E501
        :rtype: PreferedWorkspace
        """
        return util.deserialize_model(dikt, cls)

    @property
    def default_workspace_id(self) -> str:
        """Gets the default_workspace_id of this PreferedWorkspace.


        :return: The default_workspace_id of this PreferedWorkspace.
        :rtype: str
        """
        return self._default_workspace_id

    @default_workspace_id.setter
    def default_workspace_id(self, default_workspace_id: str):
        """Sets the default_workspace_id of this PreferedWorkspace.


        :param default_workspace_id: The default_workspace_id of this PreferedWorkspace.
        :type default_workspace_id: str
        """

        self._default_workspace_id = default_workspace_id

    @property
    def user_id(self) -> str:
        """Gets the user_id of this PreferedWorkspace.


        :return: The user_id of this PreferedWorkspace.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this PreferedWorkspace.


        :param user_id: The user_id of this PreferedWorkspace.
        :type user_id: str
        """

        self._user_id = user_id
