from server import util
from server.models.base_model_ import Model


class RenameDoc(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, document_id: str = None, new_name: str = None):  # noqa: E501
        """RenameDoc - a model defined in Swagger

        :param document_id: The document_id of this RenameDoc.  # noqa: E501
        :type document_id: str
        :param new_name: The new_name of this RenameDoc.  # noqa: E501
        :type new_name: str
        """
        self.swagger_types = {
            "document_id": str,
            "new_name": str,
        }

        self.attribute_map = {
            "document_id": "documentId",
            "new_name": "newName",
        }
        self._document_id = document_id
        self._new_name = new_name

    @classmethod
    def from_dict(cls, dikt) -> "RenameDoc":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RenameDoc of this RenameDoc.  # noqa: E501
        :rtype: RenameDoc
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document_id(self) -> str:
        """Gets the document_id of this RenameDoc.


        :return: The document_id of this RenameDoc.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id: str):
        """Sets the document_id of this RenameDoc.


        :param document_id: The document_id of this RenameDoc.
        :type document_id: str
        """

        self._document_id = document_id

    @property
    def new_name(self) -> str:
        """Gets the new_name of this RenameDoc.


        :return: The new_name of this RenameDoc.
        :rtype: str
        """
        return self._new_name

    @new_name.setter
    def new_name(self, new_name: str):
        """Sets the new_name of this RenameDoc.


        :param new_name: The new_name of this RenameDoc.
        :type new_name: str
        """

        self._new_name = new_name
