CAST_FIELD_TYPE = "CAST"
BOOLEAN_MULTI_CAST_FIELD_TYPE = "BOOLEAN_MULTI_CAST"
FORMULA_FIELD_TYPE = "FORMULA"
NONE_CAST_OPTION_KEY = "__none__"
DEFAULT_CAST_OPTION_KEY = "__default__"
DEPENDENT_FIELD_ALLOWED_TYPES = [
    CAST_FIELD_TYPE,
    FORMULA_FIELD_TYPE,
    BOOLEAN_MULTI_CAST_FIELD_TYPE,
]
BOOLEAN_MULTI_CAST_PERMISSIBLE_VALUES = ["yes"]
